const assert=require('node:assert/strict'),{test}=require('node:test'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {JSDOM}=require('jsdom'),dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const name of ['window','document','Element','HTMLElement','HTMLButtonElement','SVGElement','Node','Event','KeyboardEvent','WheelEvent','localStorage'])global[name]=dom.window[name];
global.crypto=crypto.webcrypto;let urls=0;global.URL.createObjectURL=()=>`blob:image-${++urls}`;const revoked=[];global.URL.revokeObjectURL=url=>revoked.push(url);
HTMLElement.prototype.scrollTo=function(){};HTMLElement.prototype.setPointerCapture=function(){};HTMLElement.prototype.hasPointerCapture=()=>false;HTMLElement.prototype.releasePointerCapture=function(){};
global.ResizeObserver=class {observe(){}disconnect(){}};
const vue=require('vue'),{loadVueSource}=require('./helpers/load-vue-source.cjs'),root=path.resolve(__dirname,'../src/views/pilot');
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
async function flush(){for(let i=0;i<10;i++){await new Promise(r=>setTimeout(r,0));await vue.nextTick();}}
const userId='11111111-1111-4111-8111-111111111111',hash=crypto.createHash('sha256').update('v04-studio-assistant:'+userId).digest('hex'),assistantId=`${hash.slice(0,8)}-${hash.slice(8,12)}-4${hash.slice(13,16)}-8${hash.slice(17,20)}-${hash.slice(20,32)}`;
function candidate(overrides={}){return {id:'candidate-1',generationIntent:'ASSET_IMAGE_EDIT',canonicalKey:'CHAR-001',assetName:'男孩',userMessageId:userId,createdAt:Date.now()-38000,status:'SUCCEEDED',outputs:[{artifactId:'image-1'}],...overrides};}
function mountAgent(t,options={}){
 const calls=[],gets=[],timers=[],cache=new Map();let entries=options.candidates||[candidate()];const props=vue.reactive({projectId:9,scriptId:2,stage:'studio',routeName:'studio',selected:{type:'ASSET',key:'CHAR-001'},studioMode:true,imageBaselines:[]});
 const setIntervalBefore=global.setInterval,clearIntervalBefore=global.clearInterval;global.setInterval=(callback,ms)=>{timers.push({callback,ms});return timers.length;};global.clearInterval=()=>{};
 const axios={get:async(url)=>{gets.push(url);return new Blob(['image']);},post:async(url,body)=>{calls.push({url,body});if(url.endsWith('/history'))return {data:{messages:[{id:userId,role:'user',content:'加点雀斑'},{id:assistantId,role:'assistant',content:'我已开始准备新的图片候选；现有资产没有被替换。'}],visionConfigured:true}};if(url.endsWith('/candidates'))return {data:structuredClone(entries)};if(options.post)return options.post(url,body);return {data:{previewHash:'hash',jobId:body.jobId}};}};
 const external=name=>name==='@/utils/axios'?{__esModule:true,default:axios}:name==='pinia'?{storeToRefs:()=>({themeSetting:vue.ref({mode:'dark'})})}:name==='@/stores/setting'?{__esModule:true,default:()=>({})}:name==='@/stores/v04ProposalWorkspace'?{useV04ProposalWorkspace:()=>({current:()=>({studioActions:{},visualSpecProposals:{}}),putStudioAction(){}})}:name==='md-editor-v3'?{MdPreview:{props:['modelValue'],render(){return vue.h('div',this.modelValue);}}}:name==='@/components/ModelPresets.vue'?{__esModule:true,default:{render:()=>null}}:require(name);
 const component=loadVueSource(path.join(root,'ProjectAgentPanel.vue'),external,cache).default,el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,props)});app.component('t-dialog',{render:()=>null});app.mount(el);
 t.after(()=>{app.unmount();el.remove();global.setInterval=setIntervalBefore;global.clearInterval=clearIntervalBefore;});
 return {el,props,calls,gets,timers,setCandidates:value=>entries=value,refresh:async()=>{timers.find(x=>x.ms===2500).callback();await flush();}};
}
const button=(el,label)=>[...el.querySelectorAll('button')].find(b=>b.textContent.trim()===label);

test('one continuous Agent feed owns request-linked candidates; pending converges to one completed result',async t=>{
 const f=mountAgent(t,{candidates:[candidate({status:'RUNNING',outputs:[]})]});await flush();assert.equal(f.el.querySelectorAll('.feed').length,1);const article=f.el.querySelector('.image-candidate');assert.ok(article.closest('.feed'));assert.equal(article.closest('.turn').querySelector('.turn-label').textContent,'Project Agent');assert.equal(f.el.querySelector('.image-candidates'),null);assert.match(f.el.querySelector('header [role=status]').textContent,/正在生成图片 · 00:3/);
 f.setCandidates([candidate()]);await f.refresh();assert.equal(f.el.querySelectorAll('.image-candidate').length,1);assert.match(f.el.querySelector('.image-candidate').textContent,/新版本已完成/);assert.doesNotMatch(f.el.querySelector('.turn.assistant').textContent,/我已开始准备|等待生成|正在生成/);assert.match(f.el.querySelector('header [role=status]').textContent,/已完成/);
 const source=fs.readFileSync(path.join(root,'ProjectAgentPanel.vue'),'utf8');assert.equal((source.match(/overflow-y:auto/g)||[]).length,1);assert.doesNotMatch(source,/image-candidates\{[^}]*overflow|max-height:38vh/);
});
test('candidate adoption stays at its image: working, explicit confirmation, success and duplicate prevention',async t=>{
 const preview=deferred(),accept=deferred();let f;f=mountAgent(t,{post:async(url)=>{if(url.endsWith('/preview'))return preview.promise;if(url.endsWith('/accept')){await accept.promise;f.setCandidates([candidate({decision:'ACCEPTED'})]);return {data:{applied:true}};}}});await flush();const article=f.el.querySelector('.image-candidate');const adopt=button(article,'采用');adopt.click();adopt.click();await flush();assert.match(article.textContent,/正在准备确认/);assert.equal(button(article,'继续修改').dataset.phase,'IDLE');assert.equal(button(article,'不要').dataset.phase,'IDLE');assert.equal(f.calls.filter(c=>c.url.endsWith('/preview')).length,1);assert.equal(f.calls.filter(c=>c.url.endsWith('/accept')).length,0);
 preview.resolve({data:{previewHash:'exact-hash',jobId:'candidate-1'}});await flush();assert.ok(article.querySelector('.candidate-confirm'));button(article,'确认采用').click();await flush();assert.match(article.querySelector('.candidate-confirm').textContent,/正在采用/);assert.ok(button(article,'正在采用…').disabled);accept.resolve();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/accept')).length,1);assert.deepEqual(f.calls.find(c=>c.url.endsWith('/accept')).body,{projectId:9,scriptId:2,jobId:'candidate-1',previewHash:'exact-hash'});f.props.imageBaselines=[{sourceJobId:'candidate-1'}];await flush();assert.match(article.textContent,/当前版本/);assert.match(f.el.textContent,/已经采用这个版本/);
});
test('adoption failure remains visible at original image and preserves confirmation for safe retry',async t=>{
 const f=mountAgent(t,{post:async url=>{if(url.endsWith('/accept'))throw new Error('network');return {data:{previewHash:'hash'}};}});await flush();button(f.el,'采用').click();await flush();button(f.el,'确认采用').click();await flush();const article=f.el.querySelector('.image-candidate');assert.match(article.querySelector('[role=alert]').textContent,/采用结果未确认/);assert.ok(button(article,'⚠ 未完成'));assert.doesNotMatch(article.textContent,/✓ 当前版本/);
});
test('candidate Lightbox supports single click, same-asset arrows, Esc, zoom and 100%',async t=>{
 const f=mountAgent(t);await flush();f.el.querySelector('.candidate-image').click();await flush();const box=document.querySelector('.studio-lightbox');assert.ok(box);assert.equal(document.querySelectorAll('.studio-lightbox').length,1);assert.ok(button(box,'100%'));const img=box.querySelector('img');Object.defineProperty(img,'naturalWidth',{value:1024});Object.defineProperty(img,'naturalHeight',{value:1024});img.dispatchEvent(new Event('load'));await flush();button(box,'100%').click();await flush();assert.equal(box.querySelector('footer [role=status]').textContent,'100%');box.querySelector('.lightbox-viewport').dispatchEvent(new WheelEvent('wheel',{bubbles:true,deltaY:-120}));await flush();assert.notEqual(box.querySelector('footer [role=status]').textContent,'100%');box.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await flush();assert.equal(document.querySelector('.studio-lightbox'),null);
});
test('old candidate is collapsed and fetched only when history opens; continue targets exact old ID',async t=>{
 const f=mountAgent(t,{candidates:[candidate(),candidate({id:'old',createdAt:1,outputs:[{artifactId:'old-image'}]})]});await flush();assert.equal(f.el.querySelectorAll('.image-candidate').length,1);assert.equal(f.gets.some(x=>x.endsWith('/old-image')),false);const details=f.el.querySelector('.candidate-history');details.open=true;details.dispatchEvent(new Event('toggle'));await flush();assert.equal(f.el.querySelectorAll('.image-candidate').length,2);assert.ok(f.gets.some(x=>x.endsWith('/old-image')));const old=f.el.querySelector('[data-candidate-id=old]');button(old,'继续修改').click();await flush();assert.equal(document.activeElement,f.el.querySelector('textarea'));assert.match(f.el.textContent,/正在继续修改此版本/);
});
test('composer pointer/keyboard resizing persists across reload and has explicit bounded separator',async t=>{
 localStorage.clear();const f=mountAgent(t);await flush();const handle=f.el.querySelector('.composer-handle');const point=(type,y)=>{const e=new Event(type,{bubbles:true});Object.assign(e,{button:0,pointerType:'mouse',pointerId:1,clientY:y});handle.dispatchEvent(e);};f.el.querySelector('.agent').getBoundingClientRect=()=>({bottom:600});point('pointerdown',500);point('pointermove',375);point('pointerup',375);await flush();assert.equal(f.el.querySelector('.composer').style.height,'225px');assert.equal(localStorage.getItem('dreamstream.v04.agent-composer-height.v1'),'225');const second=mountAgent(t);await flush();assert.equal(second.el.querySelector('.composer').style.height,'225px');second.el.querySelector('.composer-handle').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));await flush();assert.equal(second.el.querySelector('.composer').style.height,'209px');
});
test('scope switch closes Lightbox/confirmation, clears feedback and ignores late preview response',async t=>{
 const pending=deferred(),f=mountAgent(t,{post:async()=>pending.promise});await flush();f.el.querySelector('.candidate-image').click();await flush();assert.ok(document.querySelector('.studio-lightbox'));button(f.el,'采用').click();await flush();f.setCandidates([]);f.props.projectId=10;f.props.scriptId=3;await flush();pending.resolve({data:{previewHash:'old'}});await flush();assert.equal(document.querySelector('.studio-lightbox'),null);assert.equal(f.el.querySelector('.candidate-confirm'),null);assert.equal(f.el.querySelector('.image-candidate'),null);assert.ok(revoked.length>0);
});
test('reload reconstructs RUNNING activity from persisted jobs instead of ephemeral busy',async t=>{
 const f=mountAgent(t,{candidates:[candidate({status:'RUNNING',outputs:[]})]});await flush();assert.match(f.el.querySelector('header [role=status]').textContent,/正在生成图片/);const second=mountAgent(t,{candidates:[candidate({status:'RUNNING',outputs:[]})]});await flush();assert.match(second.el.querySelector('header [role=status]').textContent,/正在生成图片/);
});
test('Lightbox navigation never leaves the supplied semantic group and supports keyboard pan lifecycle',async t=>{
 const component=loadVueSource(path.join(root,'StudioImageLightbox.vue')).default,props=vue.reactive({images:[{id:'front',src:'/front.png',label:'正面'},{id:'back',src:'/back.png',label:'背面'}],index:0});const el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,{...props,onChange:index=>props.index=index,onClose:()=>props.images=[]})});app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();let box=document.querySelector('.studio-lightbox');box.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await flush();assert.equal(box.querySelector('img').getAttribute('src'),'/back.png');box.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await flush();assert.equal(props.index,1);box.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));await flush();assert.equal(props.index,0);box.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await flush();assert.equal(document.querySelector('.studio-lightbox'),null);
});
test('Drawer shows all generated views together and current picture opens shared Lightbox',async t=>{
 const cache=new Map(),review=loadVueSource(path.join(root,'studioImageReview.ts'),require,cache),Drawer=loadVueSource(path.join(root,'StudioAssetDrawer.vue'),require,cache).default,Lightbox=loadVueSource(path.join(root,'StudioImageLightbox.vue'),require,cache).default;let images;const references=['主视图','侧面','后侧','细节'].map((label,i)=>({id:String(i),src:`/ref-${i}.png`,label}));const el=document.createElement('div');document.body.append(el);const app=vue.createApp({setup(){images=review.provideStudioImageReview();return ()=>vue.h('main',[vue.h(Drawer,{item:{asset:{canonicalKey:'PROP-001',name:'海盗船',sourcePolicy:'AI_ALLOWED'},refs:[],status:'已准备',referenceJobs:{}},imageUrl:'/main.png',referenceImages:references,width:440}),vue.h(Lightbox,{images:images.group.value,index:images.index.value,onChange:index=>images.index.value=index,onClose:images.close})]);}});app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();assert.equal(el.querySelectorAll('.reference-grid img').length,4);el.querySelector('.visual img').click();await flush();assert.equal(document.querySelector('.studio-lightbox img').getAttribute('src'),'/main.png');images.close();await flush();el.querySelectorAll('.reference-grid button')[1].click();await flush();assert.equal(document.querySelector('.studio-lightbox img').getAttribute('src'),'/ref-1.png');document.querySelector('.studio-lightbox').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await flush();assert.equal(document.querySelector('.studio-lightbox img').getAttribute('src'),'/ref-2.png');assert.doesNotMatch(el.textContent,/Visual Spec|Prompt IR|草案|Execution Purpose|Reference Role/);
});
test('Studio Asset Card and Storyboard image single-click open the one shared Lightbox without preloading packs',async t=>{
 const observers=[];global.IntersectionObserver=class{constructor(cb){this.cb=cb;this.elements=[];observers.push(this);}observe(el){this.elements.push(el);}disconnect(){this.elements=[];}};t.after(()=>delete global.IntersectionObserver);
 const gets=[],calls=[],selected=vue.ref(null),asset={canonicalKey:'CHAR-001',name:'男孩',revision:1,status:'ACTIVE',sourcePolicy:'AI_ALLOWED',category:'CHAR',assetKind:'HUMAN_CHARACTER'};
 const state=vue.ref({project:{id:9,name:'Pilot'},creative:{scriptId:2,targetDuration:40,aspectRatio:'16:9',brief:'A dream',treatment:'',script:''},assets:[asset],storyboards:[{id:3,filePath:'/oss/shot.png',prompt:'Boy',duration:4}],visualSpecs:[],promptBuilds:[],reviewPlans:[],agentReferences:[]});
 const scope={projectId:9,scriptId:2},session={state,projects:vue.ref([]),selected,scope:()=>scope,loadProjects:async()=>{},restore:async()=>state.value,isCurrent:()=>true,leave:()=>state.value=null};const workspace={visualSpecProposals:{},visualSpecFailures:{},studioAssetDraftPackages:{},storyboardDrafts:[],studioActions:{}};
 const axios={get:async url=>{gets.push(url);return new Blob(['image']);},post:async(url,body)=>{calls.push({url,body});if(url.endsWith('/history'))return {data:{messages:[],visionConfigured:true}};if(url.endsWith('/current'))return {data:[]};if(url.endsWith('/jobs'))return {data:[{id:'main',...scope,canonicalKey:'CHAR-001',sourceAssetRevision:1,executionPurpose:'ASSET_MAIN_PREVIEW',status:'SUCCEEDED',outputs:[{role:'MAIN_PREVIEW',artifactId:'main-image'}]},{id:'side',...scope,canonicalKey:'CHAR-001',sourceAssetRevision:1,executionPurpose:'FULL_BODY_FRONT',status:'SUCCEEDED',outputs:[{artifactId:'side-image'}]},{id:'face',...scope,canonicalKey:'CHAR-001',sourceAssetRevision:1,executionPurpose:'FACE_HERO',status:'SUCCEEDED',outputs:[{artifactId:'face-image'}]},{id:'back',...scope,canonicalKey:'CHAR-001',sourceAssetRevision:1,executionPurpose:'FULL_BODY_BACK',status:'SUCCEEDED',outputs:[{artifactId:'back-image'}]}]};if(url.endsWith('/candidates'))return {data:[]};return {data:{}};}};
 const external=name=>name==='@/utils/axios'?{__esModule:true,default:axios}:name==='vue-router'?{useRouter:()=>({push:async()=>{}}),useRoute:()=>({query:{}})}:name==='pinia'?{storeToRefs:store=>store}:name==='@/stores/v04ProjectSession'?{useV04ProjectSession:()=>session}:name==='@/stores/v04ProposalWorkspace'?{useV04ProposalWorkspace:()=>({entries:{'9:2':workspace},current:()=>workspace,setScope(){}})}:name==='@/views/production/revision/coordinator'?{useStoryboardRevision:()=>({state:{draft:null},bind(){},setScope(){}})}:name==='@/stores/setting'?{__esModule:true,default:()=>({themeSetting:vue.ref({mode:'dark'})})}:name==='md-editor-v3'?{MdPreview:{props:['modelValue'],render(){return vue.h('p',this.modelValue);}}}:name==='@/components/ModelPresets.vue'?{__esModule:true,default:{render:()=>null}}:require(name);
 const cache=new Map();const component=loadVueSource(path.join(root,'StudioWorkspace.vue'),external,cache).default,el=document.createElement('div');document.body.append(el);const app=vue.createApp(component);app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();
 assert.equal(gets.some(x=>x.endsWith('/side-image')),false,'hidden pack high-resolution image is not downloaded on entry');for(const ob of observers)ob.cb(ob.elements.map(target=>({target,isIntersecting:true})));await flush();assert.equal(el.querySelectorAll('.asset-card img').length,3);el.querySelector('.asset-card img').click();await flush();assert.equal(document.querySelectorAll('.studio-lightbox').length,1);assert.match(document.querySelector('.studio-lightbox img').getAttribute('src'),/^blob:/);assert.equal(el.querySelector('.drawer'),null);const box=document.querySelector('.studio-lightbox');box.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await flush();box.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await flush();const last=box.querySelector('img').getAttribute('src');box.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await flush();assert.equal(box.querySelector('img').getAttribute('src'),last);el.querySelector('.asset-caption').click();await flush();assert.ok(el.querySelector('.drawer'));el.querySelector('.drawer p').click();await flush();assert.ok(el.querySelector('.drawer'));el.querySelector('.agent-panel textarea').click();await flush();assert.ok(el.querySelector('.drawer'));document.querySelector('.studio-lightbox').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await flush();assert.equal(document.querySelector('.studio-lightbox'),null);assert.ok(el.querySelector('.drawer'));document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await flush();assert.equal(el.querySelector('.drawer'),null);el.querySelector('.asset-caption').click();await flush();el.querySelector('.world-intro').click();await flush();assert.equal(el.querySelector('.drawer'),null);state.value.assets.push({...asset,canonicalKey:'CREATURE-001',name:'鲸鱼',assetKind:'CREATURE'});await flush();[...el.querySelectorAll('.asset-caption')].find(e=>e.textContent.includes('鲸鱼')).click();await flush();assert.match(el.querySelector('.drawer h2').textContent,/鲸鱼/);[...el.querySelectorAll('.asset-caption')].find(e=>e.textContent.includes('男孩')).click();await flush();assert.match(el.querySelector('.drawer h2').textContent,/男孩/);el.querySelector('.asset-card img').click();await flush();assert.ok(gets.some(x=>x.endsWith('/side-image')),'opening the visible asset loads only its own pack');document.querySelector('.studio-lightbox').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await flush();el.querySelector('.shot-card img').click();await flush();assert.equal(document.querySelector('.studio-lightbox img').getAttribute('src'),'/oss/shot.png');assert.equal(selected.value.type,'SHOT');
});
test('shared action feedback has immediate work/success/failure and ignores late old-scope completion',async t=>{
 const Button=loadVueSource(path.join(root,'StudioActionButton.vue')).default,wait=deferred(),props=vue.reactive({label:'刷新',working:'正在刷新…',success:'已刷新',scopeKey:'9:2',action:()=>wait.promise});let calls=0;const el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(Button,{...props,action:()=>{calls++;return props.action();}})});app.mount(el);t.after(()=>{app.unmount();el.remove();});el.querySelector('button').click();el.querySelector('button').click();await flush();assert.equal(calls,1);assert.match(el.textContent,/正在刷新/);props.scopeKey='10:3';await flush();wait.resolve();await flush();assert.equal(el.querySelector('button').dataset.phase,'IDLE');props.action=async()=>{throw Error('failed');};el.querySelector('button').click();await flush();assert.equal(el.querySelector('button').dataset.phase,'FAILURE');assert.ok(el.querySelector('[role=alert]'));props.action=async()=>true;el.querySelector('button').click();await flush();assert.equal(el.querySelector('button').dataset.phase,'SUCCESS');assert.match(el.textContent,/已刷新/);
});

 test('02A independent Continue/Reject/Adopt feedback and duplicate rejection',async t=>{
 const reject=deferred();const f=mountAgent(t,{post:async url=>url.endsWith('/reject')?reject.promise:{data:{previewHash:'hash'}}});await flush();const a=f.el.querySelector('.image-candidate');button(a,'继续修改').click();await vue.nextTick();assert.equal(button(a,'采用').dataset.phase,'IDLE');assert.equal(button(a,'不要').dataset.phase,'IDLE');assert.equal(button(a,'正在进入修改…').dataset.phase,'WORKING');await flush();assert.ok(button(a,'✓ 已进入修改'));const no=button(a,'不要');no.click();no.click();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/reject')).length,1);assert.equal(button(a,'采用').dataset.phase,'IDLE');assert.ok(button(a,'✓ 已进入修改'));assert.ok(button(a,'正在处理…'));reject.resolve({data:{}});await flush();assert.ok(button(a,'✓ 已放弃'));assert.equal(button(a,'采用').dataset.phase,'IDLE');
 });
 test('02A automatic Reference Pack never enters edit history; genuine V1/V2 remain',async t=>{
 const f=mountAgent(t,{candidates:[candidate({id:'v2',createdAt:200,parentCandidateId:'v1'}),candidate({id:'v1',createdAt:100}),...['FACE_HERO','SIDE_PROFILE','ASSET_MAIN_PREVIEW'].map((role,i)=>candidate({id:'auto'+i,generationIntent:role,automatic:true,targetRole:role}))]});await flush();assert.match(f.el.querySelector('.candidate-history').textContent,/历史版本（1）/);assert.equal(f.el.querySelector('[data-candidate-id=auto0]'),null);assert.equal(f.gets.length,1);const detail=f.el.querySelector('.candidate-history');detail.open=true;detail.dispatchEvent(new Event('toggle'));await flush();assert.ok(f.el.querySelector('[data-candidate-id=v1]'));assert.equal(f.el.querySelectorAll('.image-candidate').length,2);
 });
 test('02A timing uses startedAt and completedAt, never invents legacy duration',async t=>{
 const now=Date.now();const f=mountAgent(t,{candidates:[candidate({status:'RUNNING',outputs:[],createdAt:now-500000,startedAt:now-10000})]});await flush();assert.match(f.el.querySelector('.image-candidate [role=status]').textContent,/00:1/);f.setCandidates([candidate({startedAt:1000,completedAt:6000,createdAt:0})]);await f.refresh();assert.match(f.el.querySelector('.completion').textContent,/00:05/);f.setCandidates([candidate({startedAt:null,completedAt:6000})]);await f.refresh();assert.equal(f.el.querySelector('.completion').textContent.trim(),'✓ 新版本已完成');assert.doesNotMatch(f.el.textContent,/NaN/);
 });
