const assert=require('node:assert/strict'),{test}=require('node:test'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const {JSDOM}=require('jsdom'),dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const k of ['window','document','Element','HTMLElement','SVGElement','Node','Event'])global[k]=dom.window[k];
global.crypto=require('node:crypto').webcrypto;global.URL.createObjectURL=()=> 'blob:output';global.URL.revokeObjectURL=()=>{};
const vue=require('vue'),{parse,compileScript}=require('vue/compiler-sfc'),file=path.resolve(__dirname,'../src/views/pilot/OperationsConsole.vue');
const source=compileScript(parse(fs.readFileSync(file,'utf8'),{filename:file}).descriptor,{id:'ops',inlineTemplate:true}).content.replace('(import.meta as any).env.VITE_EXPERIMENTAL_COMMIT',"'test-frontend'");
const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
const status={backend:{status:'ONLINE',commit:'test-backend',dataDirectory:'disposable'},comfy:{status:'ONLINE',baseUrl:'http://127.0.0.1:8188',version:'test',devices:[],queue:{running:0,pending:0}},legacyConfig:null,routing:{routes:{SOURCE_EDIT:'KREA2_SOURCE_EDIT_V1'},disabledProfiles:[],version:0},registry:[{profile:'KREA2_SOURCE_EDIT_V1',capabilities:['SOURCE_EDIT','CHARACTER'],wiring:'AGENT_EDIT',health:'READY'},{profile:'KREA2_T2I_ASSET_V1',capabilities:['T2I'],wiring:'NOT_WIRED',health:'READY'}]};
async function flush(){for(let i=0;i<15;i++){await Promise.resolve();await vue.nextTick();}}
function mount(t){const calls=[],module={exports:{}};let held=null;const axios={post:async(url,body)=>{calls.push({url,body});if(held&&url.endsWith('/execution'))return await new Promise(r=>held.resolve=r);if(url.endsWith('/status'))return {data:structuredClone(status)};if(url.endsWith('/executions'))return {data:[{id:'trace-1',canonicalKey:'CHAR-001',status:'SUCCEEDED',executorProfile:'KREA2_SOURCE_EDIT_V1'}]};if(url.endsWith('/preview'))return {data:{request:body,previewHash:'hash',current:status.routing,proposed:{routes:body.routes,disabledProfiles:body.disabledProfiles},affectedTaskTypes:['SOURCE_EDIT'],scope:'THIS_PROJECT'}};if(url.endsWith('/execution'))return {data:{id:'trace-1',workflowGraphJson:'{"22":{"class_type":"SaveImage","inputs":{}}}',parametersJson:'{}',modelsJson:'[]',sourcesJson:'{}',referencesJson:'[]',outputArtifactIdsJson:'[]',status:'SUCCEEDED',canonicalKey:'CHAR-001'}};return {data:{applied:true}};}};
new Function('require','module','exports',compiled)(name=>name==='@/utils/axios'?{__esModule:true,default:axios}:require(name),module,module.exports);
const props=vue.reactive({projectId:9,scriptId:2}),el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(module.exports.default,props)});app.mount(el);t.after(()=>{app.unmount();el.remove();});return {el,props,calls,hold:()=>held={},release:()=>held.resolve({data:{workflowGraphJson:'{}',parametersJson:'{}',modelsJson:'[]',sourcesJson:'{}',referencesJson:'[]',outputArtifactIdsJson:'[]'}})};}
function click(f,text){const b=[...f.el.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(b,text);b.click();}
test('mounted Operations shows truthful status and keeps routing preview separate from confirmed Apply',async t=>{const f=mount(t);await flush();assert.match(f.el.textContent,/test-frontend/);assert.match(f.el.textContent,/test-backend/);click(f,'Routing');await flush();assert.match(f.el.textContent,/NOT WIRED/);const select=f.el.querySelector('.route-row select');assert.equal(select.options.length,1);assert.equal(select.value,'KREA2_SOURCE_EDIT_V1');click(f,'Preview routing');await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/apply')).length,0);const apply=[...f.el.querySelectorAll('button')].find(b=>b.textContent==='Confirm → Apply');assert.ok(apply.disabled);const checkbox=f.el.querySelector('.preview input');checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}));await flush();apply.click();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/apply')).length,1);assert.equal(f.calls.find(c=>c.url.endsWith('/apply')).body.confirmed,true);});
test('mounted history only requests graph when detail opened; actual graph available after refresh',async t=>{const f=mount(t);await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/execution')).length,0);click(f,'Executions');await flush();f.el.querySelector('tbody tr').click();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/execution')).length,1);click(f,'查看实际 JSON');await flush();assert.match(f.el.textContent,/Actual submitted Comfy API graph/);assert.match(f.el.querySelector('.graph-viewer pre').textContent,/SaveImage/);});
test('late detail after project switch cannot contaminate new project',async t=>{const f=mount(t);await flush();click(f,'Executions');await flush();f.hold();f.el.querySelector('tbody tr').click();await flush();f.props.projectId=10;await flush();f.release();await flush();assert.equal(f.el.querySelector('.outputs'),null);assert.equal([...f.el.querySelectorAll('button')].some(b=>b.textContent==='查看实际 JSON'),false);assert.ok(f.calls.some(c=>c.url.endsWith('/status')&&c.body.projectId===10));});
test('Operations is Professional-only; exact downloaded graph is persisted JSON rather than current template',()=>{const pilot=fs.readFileSync(path.resolve(__dirname,'../src/views/pilot/PilotShell.vue'),'utf8'),studio=fs.readFileSync(path.resolve(__dirname,'../src/views/pilot/StudioWorkspace.vue'),'utf8'),ops=fs.readFileSync(file,'utf8');assert.match(pilot,/OperationsConsole/);assert.doesNotMatch(studio,/OperationsConsole/);assert.match(ops,/content=actual\?detail.value.workflowGraphJson:graph.value/);});
