const assert=require('node:assert/strict'),{test}=require('node:test'),path=require('node:path'),fs=require('node:fs');
const {JSDOM}=require('jsdom'),dom=new JSDOM('<html><body></body></html>');
for(const key of ['window','document','Element','HTMLElement','SVGElement','Node','Event','KeyboardEvent'])global[key]=dom.window[key];
let urls=0;URL.createObjectURL=blob=>{assert.ok(blob instanceof Blob);return `blob:mv-${++urls}`;};URL.revokeObjectURL=()=>{};
const vue=require('vue'),{loadVueSource}=require('./helpers/load-vue-source.cjs');
const file=path.resolve(__dirname,'../src/views/pilot/MultiViewPilotPanel.vue');
const flush=async()=>{for(let i=0;i<20;i++){await Promise.resolve();await vue.nextTick();}};
const fixture=(status='COMPILED')=>({id:'experiment-1',status,canonicalKey:'CHAR-007',assetRevision:2,experimentHash:'hash',source:{type:'ACCEPTED_IDENTITY_BASELINE',width:768,height:768},sharedExecution:{seed:42,profile:'KREA2_DERIVE_CHARACTER_REFERENCE_V1'},execution:{},
 SIDE:{prompt:'same subject side-oriented; change viewpoint only',brief:{preserve:['same clothes','same barefoot state'],viewpointInstruction:['side information'],conservativeInferenceRules:[]}},
 BACK:{prompt:'same subject primarily from behind; change viewpoint only',brief:{preserve:['same clothes','same barefoot state'],viewpointInstruction:['back information'],conservativeInferenceRules:['infer unseen details conservatively']}}});
function mount(t,post){const component=loadVueSource(file,n=>n==='@/utils/axios'?{__esModule:true,default:{post:(url,body)=>url.includes("/integrity/current")?Promise.resolve({data:{input:null,context:{integrityProfile:"HUMAN"},profile:{regions:["手","脚"]},history:[]}}):post(url,body)}}:require(n)).default,props=vue.reactive({projectId:9,scriptId:2}),el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,props)});app.mount(el);t.after(()=>{app.unmount();el.remove();});return {el,props};}
const button=(el,text)=>[...el.querySelectorAll('button')].find(b=>b.textContent.includes(text));
test('MV033A Professional entry, source, both briefs, folded audit and compile never render',async t=>{
 const calls=[],{el}=mount(t,async(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return {data:[]};if(url.endsWith('/compile'))return {data:fixture()};if(url.endsWith('/artifact'))return new Blob(['image'],{type:'image/png'});throw Error(url);});await flush();button(el,'编译男孩').click();await flush();
 assert.match(el.textContent,/Multi-View Pilot|SIDE-ish|BACK-ish|side-oriented|primarily from behind/);assert.equal(el.querySelector('details').open,false);assert.ok(el.querySelector('img[alt="男孩当前主身份图"]'));assert.equal(calls.filter(c=>c.url.endsWith('/render')).length,0);assert.ok(button(el,'生成 Side / Back').disabled);
 const shell=fs.readFileSync(path.resolve(__dirname,'../src/views/pilot/PilotShell.vue'),'utf8');assert.match(shell,/<MultiViewPilotPanel v-else-if="tab==='multiview'"/);assert.match(shell,/key:'multiview',label:'Multi-View Pilot'/);
 const source=fs.readFileSync(file,'utf8');assert.doesNotMatch(source,/image-edit\/accept|auto-assets\/reconcile|draft-image\/enqueue|reference-pack\/apply/);
});
test('MV033A source review plus second confirmation, duplicate click blocked and no adoption',async t=>{
 let finish;const calls=[],{el}=mount(t,(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return Promise.resolve({data:[fixture()]});if(url.endsWith('/artifact'))return Promise.resolve(new Blob(['image'],{type:'image/png'}));if(url.endsWith('/render'))return new Promise(r=>finish=r);throw Error(url);});await flush();
 const checkbox=el.querySelector('input[type=checkbox]');checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}));await flush();button(el,'生成 Side / Back').click();await flush();assert.match(el.querySelector('[role=dialog]').textContent,/不会替换现有素材/);assert.equal(calls.filter(c=>c.url.endsWith('/render')).length,0);
 button(el,'确认生成两个').click();button(el,'确认生成两个').click();await flush();assert.equal(calls.filter(c=>c.url.endsWith('/render')).length,1);assert.deepEqual(calls.at(-1).body,{projectId:9,scriptId:2,experimentId:'experiment-1',experimentHash:'hash',confirmRender:true,sourceQualityConfirmed:true});
 finish({data:{...fixture('FAILED'),execution:{SIDE:{status:'FAILED',errorCode:'COMFY_TIMEOUT'},BACK:{status:'NOT_RUN'}}}});await flush();assert.match(el.textContent,/COMFY_TIMEOUT|NOT_RUN/);assert.equal(el.querySelector('form'),null);assert.ok(button(el,'生成 Side / Back').disabled);
});
test('MV033A remount restores Blob MAIN/SIDE/BACK, lightbox and human PASS/PARTIAL/FAIL without rerender',async t=>{
 const c=fixture('COMPLETED');c.execution={SIDE:{status:'SUCCEEDED',artifact:{artifactId:'a'}},BACK:{status:'SUCCEEDED',artifact:{artifactId:'b'}}};const calls=[];
 const {el}=mount(t,async(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return {data:[c]};if(url.endsWith('/artifact'))return new Blob(['image'],{type:'image/png'});if(url.endsWith('/evaluate'))return {data:{SIDE:body.SIDE,BACK:body.BACK}};throw Error(url);});await flush();assert.equal(el.querySelectorAll('.view-image img').length,3);assert.equal(calls.filter(c=>c.url.endsWith('/render')).length,0);
 el.querySelector('.view-image').click();await flush();assert.ok(document.body.querySelector('.studio-lightbox'));document.body.querySelector('.studio-lightbox').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));await flush();assert.equal(document.body.querySelector('.studio-lightbox'),null);
 const selects=el.querySelectorAll('form select');selects.forEach((s,i)=>{s.value=i?'FAIL':'PARTIAL_PASS';s.dispatchEvent(new Event('change',{bubbles:true}));});await flush();el.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await flush();assert.deepEqual(calls.find(c=>c.url.endsWith('/evaluate')).body,{projectId:9,scriptId:2,experimentId:'experiment-1',SIDE:'PARTIAL_PASS',BACK:'FAIL',why:''});assert.match(el.textContent,/需另行人工授权/);assert.ok(![...el.querySelectorAll('button')].some(b=>/采用|Adopt|执行 fallback/.test(b.textContent)));
});
test('MV033A scope switch ignores late compile',async t=>{
 let done;const {el,props}=mount(t,(url)=>{if(url.endsWith('/current'))return Promise.resolve({data:[]});if(url.endsWith('/compile'))return new Promise(r=>done=r);throw Error(url);});await flush();button(el,'编译男孩').click();await flush();props.projectId=10;props.scriptId=3;await flush();done({data:fixture()});await flush();assert.equal(el.querySelector('details'),null);
});
test('MV033A late old source Blob cannot populate new project',async t=>{
 let done;const {el,props}=mount(t,(url,body)=>{if(url.endsWith('/current'))return Promise.resolve({data:body.projectId===9?[fixture()]:[]});if(url.endsWith('/artifact'))return new Promise(r=>done=r);throw Error(url);});await flush();props.projectId=10;props.scriptId=3;await flush();done(new Blob(['old'],{type:'image/png'}));await flush();assert.equal(el.querySelector('img'),null);
});
test('MV033A stale experiment displays old images but cannot render',async t=>{
 const {el}=mount(t,async(url)=>url.endsWith('/current')?{data:[fixture('STALE')]}:new Blob(['image'],{type:'image/png'}));await flush();assert.match(el.textContent,/STALE/);assert.ok(button(el,'生成 Side / Back').disabled);assert.equal(el.querySelector('input[type=checkbox]'),null);
});
test('MV033A late render acknowledgement cannot refresh a different production unit',async t=>{
 let finish;const calls=[],{el,props}=mount(t,(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return Promise.resolve({data:body.projectId===9?[fixture()]:[]});if(url.endsWith('/artifact'))return Promise.resolve(new Blob(['image'],{type:'image/png'}));if(url.endsWith('/render'))return new Promise(r=>finish=r);throw Error(url);});await flush();
 const checkbox=el.querySelector('input[type=checkbox]');checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}));await flush();button(el,'生成 Side / Back').click();await flush();button(el,'确认生成两个').click();await flush();props.projectId=10;props.scriptId=3;await flush();finish({data:fixture('RENDERING_SIDE')});await flush();assert.equal(el.querySelector('details'),null);assert.equal(calls.filter(c=>c.url.endsWith('/render')).length,1);assert.equal(calls.find(c=>c.url.endsWith('/render')).body.projectId,9);
});

test('INTEGRITY mounted human issue entry saves immutable scope/hash, displays repair-only report and isolates context',async t=>{
 const calls=[],input={experimentId:'experiment-1',sourceHash:'source',assetRevision:2,visualSpecRevision:null,artifacts:{MAIN:'m',SIDE:'s',BACK:'b'}};
 const state={input,context:{integrityProfile:'HUMAN'},profile:{regions:['手','脚']},history:[]};
 const component=loadVueSource(path.resolve(__dirname,'../src/views/pilot/AssetIntegrityPanel.vue'),n=>n==='@/utils/axios'?{__esModule:true,default:{post:async(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return {data:state};if(url.endsWith('/record')){state.history=[{id:'record',freshness:'CURRENT',createdAt:1,decisions:{SIDE:'PASS',BACK:'REPAIRABLE',CROSS_VIEW:'PASS'},reports:body.reports,repairProposals:[{executionAuthorized:false,preserveOutsideRegion:true}]}];return {data:{}};}throw Error(url);}}}:require(n)).default;
 const props=vue.reactive({projectId:9,scriptId:2,experimentId:'experiment-1'}),el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,props)});app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();
 assert.match(el.textContent,/人工检查|HUMAN_INSPECTOR/);button(el,'添加 BACK').click();await flush();let issue=el.querySelector('.issue');issue.querySelector('textarea').value='脚方向不合理';issue.querySelector('textarea').dispatchEvent(new Event('input',{bubbles:true}));await flush();el.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await flush();const request=calls.find(c=>c.url.endsWith('/record'));assert.deepEqual(request.body.expectedInput,input);assert.equal(request.body.reports.BACK.issues[0].description,'脚方向不合理');assert.equal(request.body.reports.BACK.issues[0].repairability,'LOCAL_REPAIR');assert.match(el.textContent,/REPAIRABLE|仅提案，未执行/);assert.equal(calls.some(c=>/render|adopt|apply/.test(c.url)),false);
 props.projectId=10;props.scriptId=3;await flush();assert.equal(el.querySelectorAll('.issue').length,0);assert.equal(calls.at(-1).body.projectId,10);
});

test('INTEGRITY late old-project inspection cannot replace new-project context',async t=>{
 let late;const post=(url,body)=>body.projectId===9?new Promise(resolve=>late=resolve):Promise.resolve({data:{input:null,context:{integrityProfile:'VEHICLE'},profile:{regions:['车轮']},history:[]}});
 const component=loadVueSource(path.resolve(__dirname,'../src/views/pilot/AssetIntegrityPanel.vue'),n=>n==='@/utils/axios'?{__esModule:true,default:{post}}:require(n)).default,props=vue.reactive({projectId:9,scriptId:2,experimentId:'old'}),el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,props)});app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();props.projectId=10;props.scriptId=3;props.experimentId='new';await flush();assert.match(el.textContent,/VEHICLE/);late({data:{input:null,context:{integrityProfile:'HUMAN'},profile:{regions:['手']},history:[]}});await flush();assert.match(el.textContent,/VEHICLE/);assert.doesNotMatch(el.textContent,/HUMAN_INSPECTOR.*HUMAN /);
});

test('INTEGRITY03 mounted profile evidence distinguishes current resolution from frozen historical context',async t=>{
 const pass={issues:[]};const state={input:null,context:{integrityProfile:'ANIMAL',profileResolution:{confidence:'HIGH',evidence:['confirmed Visual Spec: biological animal morphology'],fallbackUsed:false}},profile:{regions:['鳍']},history:[{id:'old',createdAt:1,freshness:'CURRENT',context:{integrityProfile:'FANTASY_CREATURE',profileResolverVersion:'integrity.profile-resolver.1'},decisions:{SIDE:'PASS',BACK:'PASS',CROSS_VIEW:'PASS'},reports:{SIDE:pass,BACK:pass,CROSS_VIEW:pass},repairProposals:[]}]};
 const component=loadVueSource(path.resolve(__dirname,'../src/views/pilot/AssetIntegrityPanel.vue'),n=>n==='@/utils/axios'?{__esModule:true,default:{post:async()=>({data:state})}}:require(n)).default;const el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,{projectId:9,scriptId:2,experimentId:'experiment'})});app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();assert.match(el.textContent,/Resolved Profile: ANIMAL/);assert.match(el.textContent,/HIGH.*confirmed Visual Spec/);assert.match(el.textContent,/记录时 Profile: FANTASY_CREATURE.*integrity.profile-resolver.1/);
});

test('QA034 mounted Fast no external call, Vision explicit consent, duplicate prevention and audit visibility',async t=>{
 const calls=[],base={externalVision:{configured:true,state:'UNKNOWN',model:'fake:vision'},input:{},context:{integrityProfile:'HUMAN'},profile:{regions:['手']},history:[]};
 const empty={issues:[]},pipeline={kind:'FAST',phase:'COMPLETED',guardState:'NOT_APPLICABLE_HISTORICAL',visionEscalation:'NOT_REQUESTED',fast:{SIDE:{status:'SUSPECT'},BACK:{status:'SUSPECT'}},decisions:{SIDE:'HUMAN_REVIEW',BACK:'HUMAN_REVIEW',CROSS_VIEW:'HUMAN_REVIEW'}};let finish;
 const component=loadVueSource(path.resolve(__dirname,'../src/views/pilot/AssetIntegrityPanel.vue'),n=>n==='@/utils/axios'?{__esModule:true,default:{post:async(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return {data:structuredClone(base)};if(url.endsWith('/fast')){base.history=[{id:'fast-1',freshness:'CURRENT',createdAt:1,pipeline,decisions:pipeline.decisions,reports:{SIDE:empty,BACK:empty,CROSS_VIEW:empty}}];return {data:{}};}if(url.endsWith('/preflight')){base.externalVision={configured:true,state:'READY',model:'fake:vision',capability:{state:'INTEGRITY_VISION_READY'}};base.history.unshift({id:'cap',freshness:'CURRENT',createdAt:2,pipeline:{kind:'PREFLIGHT',phase:'COMPLETED',capability:{state:'INTEGRITY_VISION_READY'}},reports:{SIDE:empty,BACK:empty,CROSS_VIEW:empty},decisions:{}});return {data:{}};}if(url.endsWith('/vision'))return new Promise(resolve=>finish=resolve);throw Error(url);}}}:require(n)).default;
 const el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,{projectId:9,scriptId:2,experimentId:'e'})});app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();
 button(el,'运行 Fast Gate').click();await flush();assert.equal(calls.some(c=>c.url.endsWith('/vision')),false);assert.match(el.textContent,/SUSPECT.*HUMAN_REVIEW/);assert.match(el.textContent,/NOT_APPLICABLE_HISTORICAL/);
 assert.equal(Array.from(el.querySelectorAll('button')).some(b=>b.textContent.includes('Vision 影子')),false);const consent=el.querySelector('.quality-pipeline input[type=checkbox]');consent.checked=true;consent.dispatchEvent(new Event('change',{bubbles:true}));await flush();button(el,'Vision 能力预检').click();await flush();assert.equal(calls.filter(c=>c.url.endsWith('/preflight')).length,1);const consent2=el.querySelector('.quality-pipeline input[type=checkbox]');consent2.checked=true;consent2.dispatchEvent(new Event('change',{bubbles:true}));await flush();const b=button(el,'运行 Vision 影子复核');b.click();b.click();await flush();assert.equal(calls.filter(c=>c.url.endsWith('/vision')).length,1);assert.equal(calls.find(c=>c.url.endsWith('/vision')).body.confirmExternalInspection,true);assert.equal(calls.find(c=>c.url.endsWith('/vision')).body.fastReportId,'fast-1');assert.equal(calls.find(c=>c.url.endsWith('/vision')).body.forceShadow,true);finish({data:{}});await flush();
 assert.equal(calls.some(c=>/render|adopt|apply/.test(c.url)),false);
});

test('QA034H3 preflight visibility is model based even before Fast or after historical PASS; config stale reload',async t=>{
 const calls=[],empty={issues:[]},base={input:{},context:{integrityProfile:'HUMAN'},profile:{regions:[]},externalVision:{configured:true,state:'UNKNOWN',model:'qwen3.8-flash'},history:[]};
 const component=loadVueSource(path.resolve(__dirname,'../src/views/pilot/AssetIntegrityPanel.vue'),n=>n==='@/utils/axios'?{__esModule:true,default:{post:async(url,body)=>{calls.push({url,body});return {data:structuredClone(base)};}}}:require(n)).default;
 const el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,{projectId:9,scriptId:2,experimentId:'e'})});app.mount(el);t.after(()=>{app.unmount();el.remove();});await flush();assert.ok(button(el,'Vision 能力预检'));assert.equal(calls.length,1);assert.ok(button(el,'Vision 能力预检').disabled);
 base.history=[{id:'fast',freshness:'CURRENT',createdAt:1,pipeline:{kind:'FAST',phase:'COMPLETED',fast:{SIDE:{status:'PASS'},BACK:{status:'PASS'}},decisions:{SIDE:'PASS',BACK:'PASS'}},effectiveFast:{SIDE:{coarseStatus:'PASS',unverifiedFor:['FINE_STRUCTURE']},BACK:{coarseStatus:'PASS',unverifiedFor:['FINE_STRUCTURE'],humanConflict:'FAST_HUMAN_CONFLICT',humanDecision:'REPAIRABLE'}},effectiveDecisions:{SIDE:'HUMAN_REVIEW',BACK:'HUMAN_REVIEW'},reports:{SIDE:empty,BACK:empty,CROSS_VIEW:empty},decisions:{SIDE:'PASS',BACK:'PASS'}}];button(el,'刷新检查记录').click();await flush();assert.ok(button(el,'Vision 能力预检'));assert.match(el.textContent,/COARSE PASS.*UNVERIFIED/);assert.match(el.textContent,/FAST_HUMAN_CONFLICT.*REPAIRABLE/);
 base.externalVision.state='READY';button(el,'刷新检查记录').click();await flush();assert.equal(button(el,'Vision 能力预检'),undefined);assert.ok(button(el,'运行 Vision 影子复核'));assert.equal(calls.some(c=>c.url.endsWith('/vision')||c.url.endsWith('/preflight')),false);
 base.externalVision.state='STALE';button(el,'刷新检查记录').click();await flush();assert.ok(button(el,'Vision 能力预检'));assert.equal(button(el,'运行 Vision 影子复核'),undefined);
});

function qaClock(t){let now=10000,id=0;const timers=new Map();t.mock.method(Date,'now',()=>now);t.mock.method(global,'setTimeout',(fn,ms)=>{const key=++id;timers.set(key,{fn,at:now+ms,ms:0});return key;});t.mock.method(global,'setInterval',(fn,ms)=>{const key=++id;timers.set(key,{fn,at:now+ms,ms});return key;});for(const name of ['clearTimeout','clearInterval'])t.mock.method(global,name,key=>timers.delete(key));return {timers,async tick(ms){const end=now+ms;while(true){const entry=[...timers].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!entry)break;const [key,v]=entry;now=v.at;if(v.ms)v.at+=v.ms;else timers.delete(key);v.fn();await flush();}now=end;await flush();}};}
function mountQA(t,post){const component=loadVueSource(path.resolve(__dirname,'../src/views/pilot/AssetIntegrityPanel.vue'),n=>n==='@/utils/axios'?{__esModule:true,default:{post}}:require(n)).default,props=vue.reactive({projectId:9,scriptId:2,experimentId:'e'}),el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(component,props)});app.mount(el);t.after(()=>{app.unmount();el.remove();});return {el,props,app};}
function qaState(ready=true){const empty={issues:[]};return {input:{},context:{integrityProfile:'HUMAN'},profile:{regions:[]},externalVision:{configured:true,state:ready?'READY':'UNKNOWN',model:'openai:qwen3.8-flash',configSignature:'cfg'},history:[{id:'fast-1',createdAt:1,freshness:'CURRENT',pipeline:{kind:'FAST',phase:'COMPLETED',fast:{SIDE:{status:'PASS'},BACK:{status:'PASS'}},decisions:{}},reports:{SIDE:empty,BACK:empty,CROSS_VIEW:empty},decisions:{}}]};}
function qaRecord(kind,phase,extras={}){const empty={issues:[]};return {id:kind+'-run',createdAt:1791288360000,freshness:'CURRENT',pipeline:{kind,phase,targetView:'BACK',fastReportId:'fast-1',configSignature:'cfg',...extras},reports:{SIDE:empty,BACK:empty,CROSS_VIEW:empty},decisions:{}};}
function qaConsent(el){const input=el.querySelector('.quality-pipeline input[type=checkbox]');input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));}

test('QA034H4 Vision immediate running label, elapsed, single submit, STARTED poll and persisted completion',async t=>{
 const clock=qaClock(t),base=qaState(),calls=[];let finish;
 const {el}=mountQA(t,(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return Promise.resolve({data:structuredClone(base)});if(url.endsWith('/vision'))return new Promise(r=>finish=r);throw Error(url);});await flush();qaConsent(el);await flush();const b=button(el,'运行 Vision 影子复核');b.click();b.click();await flush();assert.match(b.textContent,/正在审核 BACK… 0s/);assert.ok(b.disabled);assert.equal(calls.filter(c=>c.url.endsWith('/vision')).length,1);
 await clock.tick(1000);assert.match(b.textContent,/1s/);base.history.unshift(qaRecord('VISION','STARTED'));await clock.tick(1000);assert.match(el.textContent,/VISION · BACK · qwen3.8-flash · STARTED/);assert.equal(calls.filter(c=>c.url.endsWith('/current')).length,2);
 base.history[0]=qaRecord('VISION','COMPLETED',{visionEscalation:'USED',visionAudit:{modelName:'qwen3.8-flash'}});await clock.tick(2000);assert.match(el.textContent,/✓ Vision BACK 审核完成/);const reads=calls.length;await clock.tick(6000);assert.equal(calls.length,reads,'terminal evidence stops polling even while submit response is pending');finish({data:base.history[0]});await flush();qaConsent(el);await flush();assert.ok(!button(el,'运行 Vision 影子复核').disabled);assert.equal(clock.timers.size,0);assert.equal(calls.filter(c=>c.url.endsWith('/vision')).length,1);
});

test('QA034H4 Preflight uses identical lifecycle and truthful failed/completed audit titles',async t=>{
 const clock=qaClock(t),base=qaState(false),calls=[];let finish;
 const {el}=mountQA(t,(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return Promise.resolve({data:structuredClone(base)});if(url.endsWith('/preflight'))return new Promise(r=>finish=r);throw Error(url);});await flush();qaConsent(el);await flush();const b=button(el,'Vision 能力预检');b.click();b.click();await flush();assert.match(b.textContent,/正在预检 Vision… 0s/);await clock.tick(1000);assert.match(b.textContent,/1s/);
 base.history.unshift(qaRecord('PREFLIGHT','STARTED'));base.externalVision.state='PENDING';await clock.tick(1000);assert.match(b.textContent,/正在预检 Vision/);assert.ok(el.contains(b));assert.match(el.textContent,/PREFLIGHT · qwen3.8-flash · STARTED/);
 base.externalVision.state='FAILED';base.history[0]=qaRecord('PREFLIGHT','COMPLETED',{capability:{modelName:'qwen3.8-flash',state:'UNAVAILABLE',errorCode:'VISION_SINGLE_IMAGE_TIMEOUT'}});await clock.tick(2000);assert.match(el.textContent,/✕ Vision 能力预检失败：VISION_SINGLE_IMAGE_TIMEOUT/);assert.match(el.textContent,/PREFLIGHT · qwen3.8-flash · FAILED/);assert.match(el.textContent,/FAST · Local CPU · COMPLETED/);finish({data:base.history[0]});await flush();assert.equal(clock.timers.size,0);assert.equal(calls.filter(c=>c.url.endsWith('/preflight')).length,1);
 // A cached successful server record is truth, not inferred from HTTP 200.
 qaConsent(el);await flush();button(el,'Vision 能力预检').click();await flush();const completed=qaRecord('PREFLIGHT','COMPLETED',{capability:{modelName:'qwen3.8-flash',state:'INTEGRITY_VISION_READY'}});base.history.unshift(completed);finish({data:completed});await flush();assert.match(el.textContent,/✓ Vision 能力预检完成/);assert.match(el.textContent,/PREFLIGHT · qwen3.8-flash · COMPLETED · PASS/);
});

test('QA034H4 failed Vision result shows server error code, response-only success is never guessed',async t=>{
 const clock=qaClock(t),base=qaState(),calls=[];let finish;
 const {el}=mountQA(t,(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return Promise.resolve({data:structuredClone(base)});if(url.endsWith('/vision'))return new Promise(r=>finish=r);throw Error(url);});await flush();qaConsent(el);await flush();button(el,'运行 Vision 影子复核').click();await flush();base.history.unshift(qaRecord('VISION','COMPLETED',{visionEscalation:'FAILED',visionAudit:{modelName:'qwen3.8-flash',errorCode:'VISION_SCHEMA_FAILED'}}));finish({data:base.history[0]});await flush();assert.match(el.textContent,/✕ Vision BACK 审核失败：VISION_SCHEMA_FAILED/);assert.match(el.textContent,/VISION · BACK · qwen3.8-flash · FAILED/);assert.equal(clock.timers.size,0);
 qaConsent(el);await flush();button(el,'运行 Vision 影子复核').click();await flush();finish({data:{}});await flush();assert.match(el.textContent,/尚未读到终态/);assert.doesNotMatch(el.querySelector('.run-result').textContent,/审核完成/);assert.equal(clock.timers.size,0);
});

test('QA034H4 switching any scope cancels timers; late poll and submit cannot touch new unit; unmount stops polling',async t=>{
 const clock=qaClock(t),base=qaState(),calls=[];let finish,lateRead;
 const {el,props,app}=mountQA(t,(url,body)=>{calls.push({url,body});if(url.endsWith('/vision'))return new Promise(r=>finish=r);if(url.endsWith('/current')){if(body.projectId===9&&calls.filter(c=>c.url.endsWith('/current')).length>1)return new Promise(r=>lateRead=r);return Promise.resolve({data:body.projectId===9?structuredClone(base):{...qaState(),context:{integrityProfile:'VEHICLE'}}});}throw Error(url);});await flush();qaConsent(el);await flush();button(el,'运行 Vision 影子复核').click();await flush();await clock.tick(2000);props.projectId=10;props.scriptId=3;props.experimentId='other';await flush();assert.match(el.textContent,/VEHICLE/);assert.equal(clock.timers.size,0);lateRead({data:structuredClone(base)});finish({data:qaRecord('VISION','COMPLETED')});await flush();assert.match(el.textContent,/VEHICLE/);assert.doesNotMatch(el.textContent,/✓ Vision BACK/);const count=calls.length;await clock.tick(10000);assert.equal(calls.length,count);
 qaConsent(el);await flush();button(el,'运行 Vision 影子复核').click();await flush();assert.ok(clock.timers.size>0);app.unmount();assert.equal(clock.timers.size,0);finish({data:qaRecord('VISION','COMPLETED')});await flush();
});

test('QA034H4 request failure without terminal record stops polling and reports explicit server rejection',async t=>{
 const clock=qaClock(t),base=qaState(false),calls=[];let reject;
 const {el}=mountQA(t,(url,body)=>{calls.push({url,body});if(url.endsWith('/current'))return Promise.resolve({data:structuredClone(base)});if(url.endsWith('/preflight'))return new Promise((_,r)=>reject=r);throw Error(url);});await flush();qaConsent(el);await flush();button(el,'Vision 能力预检').click();await flush();await clock.tick(2000);reject({response:{data:{code:'INTEGRITY_INPUT_STALE'}}});await flush();assert.match(el.textContent,/请求失败：INTEGRITY_INPUT_STALE/);assert.equal(clock.timers.size,0);const count=calls.length;await clock.tick(10000);assert.equal(calls.length,count);assert.equal(calls.filter(c=>c.url.endsWith('/preflight')).length,1);
});
