const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {JSDOM}=require('jsdom'),dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const name of ['window','document','Element','HTMLElement','SVGElement','Node','Event'])global[name]=dom.window[name];
const vue=require('vue'),{loadVueSource}=require('./helpers/load-vue-source.cjs'),root=path.resolve(__dirname,'../src/views/pilot');
const use=loadVueSource(path.join(root,'assetPreparationFeedback.ts')).useAssetPreparationFeedback,Panel=loadVueSource(path.join(root,'AssetPreparationFeedback.vue')).default;
const scope={projectId:9,scriptId:2},req='11111111-1111-4111-8111-111111111111';
const flush=async()=>{for(let n=0;n<4;n++){await new Promise(r=>setTimeout(r,0));await vue.nextTick();}};
function fixture(t,options={}){const calls=[],reads=[],storage=new Map();const controller=use({confirm:()=>options.confirm!==false,uuid:()=>req,storage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k),removeItem:k=>storage.delete(k)},post:async b=>{calls.push(b);return options.post?options.post(b):{status:'SUBMITTED',requestId:req};},current:async b=>{reads.push(b);return options.current?options.current(b):{request:null};}});controller.bind(scope);const el=document.createElement('div');document.body.append(el);const app=vue.createApp({render:()=>vue.h(Panel,{controller})});app.mount(el);t.after(()=>{app.unmount();el.remove();});return {controller,el,calls,reads,storage};}
test('cancel is not failure; mounted confirm performs one request with immediate busy feedback',async t=>{const cancel=fixture(t,{confirm:false});cancel.el.querySelectorAll('button')[1].click();await flush();assert.equal(cancel.calls.length,0);assert.equal(cancel.controller.state.phase,'IDLE');assert.doesNotMatch(cancel.el.textContent,/未完成|失败/);let resolve;const f=fixture(t,{post:()=>new Promise(r=>resolve=r)});f.el.querySelectorAll('button')[1].click();f.el.querySelectorAll('button')[1].click();await flush();assert.equal(f.calls.length,1);assert.match(f.el.textContent,/正在提交/);assert.equal(f.el.querySelectorAll('button')[1].disabled,true);resolve({status:'SUBMITTED',requestId:req});await flush();assert.match(f.el.textContent,/已提交/);assert.doesNotMatch(f.el.textContent,/图片已完成/);assert.match(f.el.querySelectorAll('button')[1].textContent,/一键重新准备全部资产/);});
test('reject shows actual reason, code and recovery entry; old success cannot overwrite rejection',async t=>{const f=fixture(t,{post:()=>{throw {code:'DIRECTOR_AB_NOT_READY',message:'素材参考已变化，请先重新确认导演'};}});f.el.querySelectorAll('button')[1].click();await flush();assert.equal(f.controller.state.phase,'REJECTED');assert.match(f.el.textContent,/素材参考已变化/);assert.match(f.el.textContent,/审阅并重新确认导演方向/);assert.match(f.el.textContent,/DIRECTOR_AB_NOT_READY/);f.controller.observe({latest:{phase:'ADMITTED'}});assert.equal(f.controller.state.phase,'REJECTED');});
test('new/replay/existing batch statuses are truthful; failure journal is visible',async t=>{for(const status of ['SUBMITTED','REPLAYED','ALREADY_RUNNING','ALREADY_PREPARED']){const f=fixture(t,{post:async()=>({status,requestId:req})});await f.controller.run(true);assert.equal(f.controller.state.phase,status);assert.doesNotMatch(f.el.textContent,/✓.*已完成/);}const f=fixture(t);f.controller.observe({latest:{phase:'ATTENTION',errorCode:'VISUAL_PREPARATION_FAILED'}});await flush();assert.equal(f.controller.state.phase,'FAILED');assert.match(f.el.textContent,/VISUAL_PREPARATION_FAILED/);});
test('lost response checks same request; same body retry and backend replay never create a new identity',async t=>{let fail=true;const f=fixture(t,{post:async()=>{if(fail)throw {isAxiosError:true,code:'ECONNABORTED'};return {status:'REPLAYED',requestId:req};}});await f.controller.run(true,'CHAR-001');assert.equal(f.controller.state.phase,'UNCERTAIN');await f.controller.run(true);assert.equal(f.calls.length,1);assert.equal(f.reads[0].requestId,req);fail=false;await f.controller.run(false,undefined,true);assert.deepEqual(f.calls[1],f.calls[0]);assert.equal(f.controller.state.phase,'REPLAYED');assert.equal(f.storage.size,0);});
test('late response cannot pollute switched scope; accepted request remains accepted when refresh fails',async t=>{let resolve;const f=fixture(t,{post:()=>new Promise(r=>resolve=r)});const pending=f.controller.run(true);f.controller.bind({...scope,scriptId:3});resolve({status:'SUBMITTED',requestId:req});await pending;assert.equal(f.controller.state.phase,'IDLE');const g=fixture(t,{current:()=>{throw Error('offline');}});await g.controller.run(true);assert.equal(g.controller.state.phase,'SUBMITTED');assert.match(g.controller.state.message,/不要重复提交/);});
test('pending identity survives bind/reload and readonly status proves admitted original request',async t=>{const f=fixture(t,{post:()=>{throw {isAxiosError:true,code:'ERR_NETWORK'};},current:async()=>({request:{phase:'ADMITTED',requestId:req,batchId:'batch'}})});await f.controller.run(true);f.controller.bind({...scope,scriptId:3});f.controller.bind(scope);assert.equal(f.controller.state.phase,'UNCERTAIN');await f.controller.check();assert.equal(f.controller.state.phase,'ADMITTED');assert.equal(f.calls.length,1);assert.equal(f.storage.size,0);});
