const assert=require('node:assert/strict'),{test}=require('node:test'),path=require('node:path'),fs=require('node:fs');const {JSDOM}=require('jsdom'),dom=new JSDOM('<html><body></body></html>');for(const n of ['window','document','Element','HTMLElement','SVGElement','Node','Event'])global[n]=dom.window[n];const vue=require('vue'),{loadVueSource}=require('./helpers/load-vue-source.cjs'),file=path.resolve(__dirname,'../src/views/pilot/DirectorPanel.vue');
const flush=async()=>{for(let i=0;i<5;i++){await Promise.resolve();await vue.nextTick();}};const button=(el,text)=>[...el.querySelectorAll('button')].find(b=>b.textContent.trim()===text);
function proposal(){return {id:'p1',status:'DRAFT',projectBible:{globalVisualDNA:{artStyle:'电影式梦境',atmosphere:'敬畏',colorLanguage:['冷蓝月夜'],materialLanguage:['蓝色梦物质']},narrativeVisualRoles:[{canonicalKey:'CHAR-003',narrativeFunction:'阈限巨物',emotionalRead:'敬畏优先，危险其次',requiredAudiencePerception:['古老、威严']}],transformationLineage:[{from:'CHAR-002',to:'BRAND-001',relationType:'COMPOSITION_RESOLUTION'}]},unitProjection:{emotionalArc:[{emotion:'静谧'},{emotion:'敬畏'}]},diff:[{section:'narrativeVisualRoles',label:'关键角色',names:['鲸鱼'],before:[{canonicalKey:'CHAR-003',emotionalRead:'恐惧优先'}],after:[{canonicalKey:'CHAR-003',emotionalRead:'敬畏优先，危险其次'}]}]};}
function mount(t,post){const calls=[],props=vue.reactive({projectId:9,scriptId:2}),component=loadVueSource(file,n=>n==='@/utils/axios'?{__esModule:true,default:{post:(url,body)=>{calls.push({url,body});return post(url,body);}}}:require(n)).default;const el=document.createElement('div');document.body.append(el);let adopted=0;const app=vue.createApp({render:()=>vue.h(component,{...props,onAccepted:()=>adopted++})});app.mount(el);t.after(()=>{app.unmount();el.remove();});return {el,calls,props,adopted:()=>adopted};}
test('DIR031B human-readable proposal revision, inline preview and duplicate-safe confirm restores accepted version',async t=>{
 let current=null,p=proposal(),confirmResolve;const f=mount(t,async(url,body)=>{if(url.endsWith('/current'))return {data:{accepted:current,proposal:current?null:p,assetNames:[{canonicalKey:'CHAR-003',name:'鲸鱼'},{canonicalKey:'CHAR-002',name:'飞马'},{canonicalKey:'BRAND-001',name:'真实标识'}]}};if(url.endsWith('/propose'))return {data:p};if(url.endsWith('/preview'))return {data:{previewHash:'a'.repeat(64),diff:p.diff}};if(url.endsWith('/confirm')){await new Promise(r=>confirmResolve=r);current={...p,directorVersion:1,status:'CURRENT'};return {data:{directorVersion:1}};}});await flush();assert.match(f.el.textContent,/鲸鱼|敬畏优先/);assert.match(f.el.textContent,/恐惧优先.*敬畏优先/);assert.doesNotMatch(f.el.textContent,/candidateHash|schemaVersion|canonicalKey|CHAR-003|BRAND-001/);assert.equal(f.el.querySelector('pre'),null);
 const textarea=f.el.querySelector('textarea');textarea.value='鲸鱼更有敬畏感';textarea.dispatchEvent(new Event('input',{bubbles:true}));button(f.el,'修改这版候选').click();await flush();assert.equal(f.calls.find(c=>c.url.endsWith('/propose')).body.baseProposalId,'p1');assert.equal(f.calls.find(c=>c.url.endsWith('/propose')).body.userInstruction,'鲸鱼更有敬畏感');
 button(f.el,'采用视觉方向').click();await flush();assert.match(f.el.textContent,/采用前预览/);const confirm=button(f.el,'确认采用');confirm.click();confirm.click();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/confirm')).length,1);assert.match(f.el.textContent,/正在确认/);confirmResolve();await flush();assert.match(f.el.textContent,/当前导演版本 v1/);assert.match(f.el.textContent,/当前图片不会自动改变/);assert.equal(f.adopted(),1);assert.ok(f.calls.every(c=>!/(generate|reconcile|comfy|creative\/apply)/.test(c.url)));
 const reload=mount(t,async()=>({data:{accepted:{...p,directorVersion:1,status:'STALE'},proposal:null,assetNames:[]}}));await flush();assert.match(reload.el.textContent,/需要重新确认/);assert.match(reload.el.textContent,/v1/);
});
test('DIR031B late unit replies cannot populate new unit and applied-but-refresh-failed only retries reads',async t=>{
 let release;const f=mount(t,()=>new Promise(r=>release=r));await flush();const old=release;f.props.projectId=10;f.props.scriptId=3;await flush();old({data:{proposal:proposal(),assetNames:[]}});await flush();assert.doesNotMatch(f.el.textContent,/敬畏优先/);release({data:{accepted:null,proposal:null}});await flush();
 let reads=0;const p=proposal(),second=mount(t,async url=>{if(url.endsWith('/current')){if(++reads===2)throw Error('refresh lost');return {data:{proposal:reads===1?p:null,accepted:reads>1?{...p,status:'CURRENT',directorVersion:1}:null}};}if(url.endsWith('/preview'))return {data:{previewHash:'b'.repeat(64),diff:[]}};return {data:{directorVersion:1}};});await flush();button(second.el,'采用视觉方向').click();await flush();button(second.el,'确认采用').click();await flush();assert.ok(button(second.el,'重试读取已确认版本'));assert.equal(button(second.el,'采用视觉方向'),undefined);button(second.el,'重试读取已确认版本').click();await flush();assert.equal(second.calls.filter(c=>c.url.endsWith('/confirm')).length,1);assert.match(second.el.textContent,/v1/);
});
test('DIR031B uncertain confirmation retries the identical scope/proposal/hash, never a new command',async t=>{let confirmations=0;const p=proposal(),f=mount(t,async url=>{if(url.endsWith('/current'))return {data:{proposal:p}};if(url.endsWith('/preview'))return {data:{previewHash:'c'.repeat(64),diff:[]}};if(url.endsWith('/confirm')&&++confirmations===1)throw Error('network outcome uncertain');return {data:{directorVersion:1}};});await flush();button(f.el,'采用视觉方向').click();await flush();button(f.el,'确认采用').click();await flush();button(f.el,'确认采用').click();await flush();const calls=f.calls.filter(c=>c.url.endsWith('/confirm'));assert.equal(calls.length,2);assert.deepEqual(calls[0].body,calls[1].body);});
test('DIR031B Studio connects the same Agent and Director refresh without production reconcile',()=>{const studio=fs.readFileSync(path.resolve(__dirname,'../src/views/pilot/StudioWorkspace.vue'),'utf8'),agent=fs.readFileSync(path.resolve(__dirname,'../src/views/pilot/ProjectAgentPanel.vue'),'utf8');assert.match(studio,/@director-proposal="directorPanel\?\.reload\(\)"/);assert.match(agent,/directorProposal\)emit\("director-proposal"\)/);assert.match(agent,/当前图片不会自动改变/);});
