const {loadVueSource}=require('./helpers/load-vue-source.cjs');
const assert=require('node:assert/strict'),{test}=require('node:test'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const {JSDOM}=require('jsdom'),dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const k of ['window','document','Element','HTMLElement','SVGElement','Node','Event'])global[k]=dom.window[k];
global.URL.createObjectURL=()=> 'blob:test-image';global.URL.revokeObjectURL=()=>{};global.crypto=require('node:crypto').webcrypto;global.HTMLElement.prototype.scrollTo=function(){};
const vue=require('vue'),{parse,compileScript}=require('vue/compiler-sfc');
const file=path.resolve(__dirname,'../src/views/pilot/ProjectAgentPanel.vue');const descriptor=parse(fs.readFileSync(file,'utf8'),{filename:file}).descriptor;
const compiled=ts.transpileModule(compileScript(descriptor,{id:'agent',inlineTemplate:true}).content,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
async function flush(){for(let i=0;i<12;i++){await Promise.resolve();await vue.nextTick();}}
function mount(t,studioMode=true,candidates=[]){
 const calls=[],preview={projectId:9,scriptId:2,canonicalKey:'CHAR-001',assetName:'Boy',attachmentId:'attachment-a',role:'GENERAL',previewHash:'a'.repeat(64),notice:'旧图保留，不改变文字设定与生产绑定。'};
 let held=null,reply=null;const axios={get:async()=>new Blob(['image']),post:async(url,body)=>{calls.push({url,body});if(url.endsWith('/history'))return {data:{messages:[{id:'user-image',role:'user',content:'上传图',attachments:[{id:'attachment-a',name:'boy.png'}]}],visionConfigured:true}};if(url.endsWith('/candidates'))return {data:candidates.map(c=>({...c,generationIntent:c.generationIntent??'ASSET_IMAGE_EDIT'}))};if(url.endsWith('/studio-turn')&&reply)return {data:reply};if(url.endsWith('/studio-turn'))return {data:{mode:'ASSET_IMAGE_BASELINE',baselinePreview:preview,reply:'请确认使用',userMessageId:'user-2',assistantMessageId:'reply-2'}};if(url.endsWith('/confirm'))return held?await new Promise(r=>held.resolve=r):{data:{applied:true}};return {data:{}};}};
 const module={exports:{}};new Function('require','module','exports',compiled)(id=>{
 if(id==='@/utils/axios')return {__esModule:true,default:axios};if(id==='pinia')return {storeToRefs:()=>({themeSetting:vue.ref({mode:'dark'})})};if(id==='@/stores/setting')return {__esModule:true,default:()=>({})};if(id==='@/stores/v04ProposalWorkspace')return {useV04ProposalWorkspace:()=>({setScope(){},current:()=>({studioActions:{},visualSpecProposals:{}}),putStudioAction(){}})};if(id==='md-editor-v3')return {MdPreview:vue.defineComponent({render:()=>vue.h('div','reply')})};if(id.endsWith('ModelPresets.vue'))return {__esModule:true,default:vue.defineComponent({render:()=>null})};if(id.startsWith('.'))return loadVueSource(path.resolve(path.dirname(file),id));return require(id);},module,module.exports);
 const props=vue.reactive({projectId:9,scriptId:2,stage:'studio',routeName:'studio',studioMode,selected:{type:'ASSET',key:'CHAR-001'}}),el=document.createElement('div');document.body.append(el);let changes=0;
 const app=vue.createApp({render:()=>vue.h(module.exports.default,{...props,'onProduction-asset-applied':()=>changes++})});app.component('t-dialog',vue.defineComponent({render:()=>null}));app.mount(el);t.after(()=>{app.unmount();el.remove();});return {el,calls,props,reply:value=>reply=value,changes:()=>changes,hold:()=>held={},release:()=>held.resolve({data:{applied:true}})};
}
async function send(f){await flush();const area=f.el.querySelector('textarea');area.value='以后以这张作为男孩基准图';area.dispatchEvent(new Event('input',{bubbles:true}));await flush();const send=[...f.el.querySelectorAll('button')].find(b=>b.textContent.trim()==='发送');assert.ok(send);send.click();await flush();}
test('Studio actual mounted turn previews image+asset, confirm is explicit and technical selectors stay Professional',async t=>{
 const f=mount(t);await send(f);const panel=f.el.querySelector('[aria-label="确认图片基准"]');assert.ok(panel,JSON.stringify(f.calls)+f.el.textContent);assert.match(panel.textContent,/Boy/);assert.ok(panel.querySelector('img'));assert.equal(f.el.querySelector('.reference-actions'),null);assert.equal(f.calls.filter(c=>c.url.endsWith('/confirm')).length,0);
 [...panel.querySelectorAll('button')].find(b=>b.textContent==='确认使用').click();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/confirm')).length,1);assert.deepEqual(f.calls.find(c=>c.url.endsWith('/confirm')).body,{projectId:9,scriptId:2,canonicalKey:'CHAR-001',attachmentId:'attachment-a',role:'GENERAL',previewHash:'a'.repeat(64)});assert.equal(f.el.querySelector('[aria-label="确认图片基准"]'),null);assert.equal(f.changes(),1);
 const professional=mount(t,false);await flush();assert.ok(professional.el.querySelector('.reference-actions select'));
});
test('mounted cancel does not apply; late confirmation cannot refresh switched project',async t=>{
 const f=mount(t);await send(f);let panel=f.el.querySelector('[aria-label="确认图片基准"]');[...panel.querySelectorAll('button')].find(b=>b.textContent==='取消').click();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/confirm')).length,0);
 await send(f);f.hold();panel=f.el.querySelector('[aria-label="确认图片基准"]');[...panel.querySelectorAll('button')].find(b=>b.textContent==='确认使用').click();await flush();f.props.projectId=10;f.props.scriptId=3;await flush();f.release();await flush();assert.equal(f.changes(),0);assert.equal(f.el.querySelector('[aria-label="确认图片基准"]'),null);
});
test('card and drawer use bound baseline before old accepted/MAIN images; role selection stays independent',()=>{
 const text=fs.readFileSync(path.resolve(__dirname,'../src/views/pilot/StudioWorkspace.vue'),'utf8'),script=parse(text).descriptor.scriptSetup.content,tree=ts.createSourceFile('studio.ts',script,ts.ScriptTarget.Latest,true),node=tree.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='imageFor');
 const fn=new Function('referenceImages','draftImages',ts.transpileModule(node.getText(tree)+'\nreturn imageFor;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText)({value:{upload:'blob:uploaded',face:'blob:face'}},{value:{old:'blob:old'}});
 const item={baseline:{attachmentId:'upload'},imageBaselines:[{attachmentId:'face',role:'FACE_HERO'}],acceptedImageJob:{id:'old'},imageJob:{id:'old',status:'SUCCEEDED'},referenceJobs:{},refs:[]};assert.equal(fn(item),'blob:uploaded');assert.equal(fn({...item,selectedPurpose:'FACE_HERO'}),'blob:face');assert.equal(fn({...item,baseline:null}),'blob:old');
});
test('mounted explicit continue sends parent; return-to-baseline text clears continuation for subsequent requests',async t=>{
 const f=mount(t,true,[{id:'candidate-v1',canonicalKey:'CHAR-001',assetName:'Boy',status:'SUCCEEDED',outputs:[{artifactId:'artifact-v1'}]}]);f.reply({mode:'DISCUSS',reply:'讨论',userMessageId:'u2',assistantMessageId:'a2'});await flush();[...f.el.querySelectorAll('button')].find(b=>b.textContent==='继续修改').click();await flush();const area=f.el.querySelector('textarea');area.value='继续修改，眼睛再自然一点';area.dispatchEvent(new Event('input',{bubbles:true}));await flush();[...f.el.querySelectorAll('button')].find(b=>b.textContent==='发送').click();await flush();assert.equal(f.calls.find(c=>c.url.endsWith('/studio-turn')).body.parentCandidateId,'candidate-v1');area.value='回到基准图';area.dispatchEvent(new Event('input',{bubbles:true}));await flush();[...f.el.querySelectorAll('button')].find(b=>b.textContent==='发送').click();await flush();assert.equal(f.calls.filter(c=>c.url.endsWith('/studio-turn'))[1].body.parentCandidateId,undefined);assert.equal(f.el.querySelector('.continuing'),null);
});
