<template><button v-bind="$attrs" type="button" :disabled="disabled || state.phase==='WORKING'" :data-phase="state.phase" :aria-busy="state.phase==='WORKING'" @click="run"><span v-if="state.phase==='WORKING'" class="spinner" aria-hidden="true" />{{ state.phase==='IDLE'?label:state.phase==='WORKING'?working:state.phase==='SUCCESS'?'✓ '+success:'⚠ 未完成' }}</button><span v-if="state.phase==='FAILURE'" class="action-error" role="alert">这次操作未完成，请检查当前状态后重试。</span></template>
<script setup lang="ts">
import {computed,onBeforeUnmount,watch} from 'vue';import {useStudioActionFeedback} from './studioActionFeedback';
const props=withDefaults(defineProps<{label:string;working?:string;success?:string;disabled?:boolean;scopeKey?:string;action:()=>unknown|Promise<unknown>}>(),{working:'正在处理…',success:'已完成'});
defineOptions({inheritAttrs:false});
const feedback=useStudioActionFeedback(),state=computed(()=>feedback.state('button'));let timer:ReturnType<typeof setTimeout>|undefined;
async function run(){if(props.disabled||state.value.phase==='WORKING')return;const key=props.scopeKey;let cancelled=false;if(timer)clearTimeout(timer);const ok=await feedback.run('button',props.working,props.success,async()=>{const result=await props.action();if(result===null)cancelled=true;else if(result===false)throw new Error('not completed');});if(cancelled&&key===props.scopeKey){feedback.reset();return;}if(ok&&key===props.scopeKey)timer=setTimeout(()=>feedback.reset(),2500);}
watch(()=>props.scopeKey,()=>{if(timer)clearTimeout(timer);feedback.reset();});onBeforeUnmount(()=>{if(timer)clearTimeout(timer);feedback.reset();});
</script>
<style scoped>
button{border:1px solid var(--td-component-border);border-radius:6px;background:var(--td-bg-color-secondarycontainer);color:var(--td-text-color-primary);padding:.4rem .65rem;cursor:pointer}button:hover:not(:disabled){border-color:var(--td-brand-color);filter:brightness(1.12)}button:active:not(:disabled){transform:translateY(1px)}button:disabled{opacity:.55;cursor:default}button[data-phase=WORKING]{color:var(--td-brand-color);background:color-mix(in srgb,var(--td-brand-color) 12%,var(--td-bg-color-container))}button[data-phase=SUCCESS]{color:var(--td-success-color)}button[data-phase=FAILURE],.action-error{color:var(--td-error-color)}.action-error{font-size:.75rem}.spinner{display:inline-block;width:.7em;height:.7em;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;animation:spin 1s linear infinite;margin-right:.35rem}@keyframes spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.spinner{animation:none}}
</style>
